import Head from "next/head";
import Navbar from "../components/Navbar";

export default function index() {
  return (
    <div className="app">
      <Head>
        <title>E|comerce</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Navbar />
    </div>
  );
}
