import Head from "next/head";
import Product from "../components/product";

//----------------------------
export async function getStaticProps() {
  const req = await fetch("https://fakestoreapi.com/products");
  const products = await req.json();
  return { props: { products } };
}
export default function index({ products }) {
  return (
    <main className="container">
      <div className="main">
        {products.map((product) => (
          <Product key={product.id} product={product} />
        ))}
      </div>
    </main>
  );
}

{
  /* <Head>
  <title>E|comerce</title>
  <meta name="description" content="Generated by create next app" />
</Head> */
}
